module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#231a0f',
        'primary-container': '#9a1a1a',
        'on-error': '#690005',
        'tertiary': '#bbcf83',
        'secondary-container': '#4d493a',
        'inverse-surface': '#f1e0ce',
        'on-surface': '#f1e0ce',
        'on-background': '#f1e0ce',
        'on-tertiary-container': '#b5c87d',
        'tertiary-fixed': '#d7eb9c',
        'surface-tint': '#ffb4ac',
        'surface-bright': '#42372b',
        'on-tertiary': '#283500',
        'secondary-fixed-dim': '#cdc6b2',
        'on-surface-variant': '#e1bfbb',
        'secondary': '#cdc6b2',
        'on-primary-container': '#ffaaa2',
        'on-secondary-fixed': '#1f1c0f',
        'on-secondary-container': '#bfb8a5',
        'surface-dim': '#1a1208',
        'surface-container': '#271e13',
        'surface': '#1a1208',
        'primary': '#ffb4ac',
        'on-primary-fixed': '#410002',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed': '#161f00',
        'outline': '#a88a86',
        'on-primary-fixed-variant': '#8f1013',
        'surface-variant': '#3d3327',
        'surface-container-highest': '#3d3327',
        'secondary-fixed': '#eae2cd',
        'on-tertiary-fixed-variant': '#3d4c0f',
        'surface-container-high': '#32281d',
        'on-secondary-fixed-variant': '#4b4738',
        'primary-fixed-dim': '#ffb4ac',
        'on-secondary': '#343022',
        'surface-container-lowest': '#140d04',
        'on-primary': '#690006',
        'inverse-on-surface': '#392f23',
        'error': '#ffb4ab',
        'primary-fixed': '#ffdad6',
        'inverse-primary': '#b12c28',
        'tertiary-fixed-dim': '#bbcf83',
        'tertiary-container': '#455416',
        'outline-variant': '#59413e',
        'error-container': '#93000a',
        'background': '#1a1208',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Frank Ruhl Libre', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
        'serif-accent': ['Newsreader', 'serif'],
      },
    },
  },
  plugins: [],
};
