name: Self-Hosted Docker Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from Secrets
        run: |
          # יצירת קובץ ה-env בתיקיית העבודה של הראנר
          echo "${{ secrets.COUP_ENV_FILE }}" > .env
          chmod 600 .env

      - name: Build and Run
        run: |
          # שימוש ב-project-name כדי למנוע התנגשויות עם פרויקטים אחרים בשרת
          docker compose --project-name coup-online down
          docker compose --project-name coup-online up -d --build

      - name: Cleanup old Docker images
        run: |
          # ניקוי אימג'ים ישנים למניעת עומס על הדיסק
          docker image prune -f
